### ISSUE TITLE
Renaming the NodeJSapp in the package.json and doing a merge see a new one added.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#132]
Renaming the NodeJSapp in the package.json and doing a merge see a new one added, so there are two NodeJSapps present.

I decided my nodejsapp was badly named - so renamed it in my package.json from cics-nodejs-invoke to cics-invoke.

I did a merge - hoping it would rename the app.

Reports doing this
zowe cics-deploy generate bundle --merge --ow
    define : NODEJSAPP "cics-invoke" with startscript "server.js"
    create : nodejsapps\cics-invoke.nodejsapp
    create : nodejsapps\cics-invoke.profile
 overwrite : .zosattributes
     merge : META-INF\cics.xml
CICS Bundle generated with bundleid "cics-invoke"

When I look in the manifest - it has added another NODEJSAPP not renamed one., and the bundle parts are present too, so I have now 2 nodejsapps instead of one.

**Comment by ChrisAtkinson1** [comment]
[Before.zip](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3156866/Before.zip)
[After.zip](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3156867/After.zip)

**Comment by pcoop** [comment]
Yup, this is what it's supposed to do, it merges any freshly generated content into an existing manifest.

This scenario is the reason we added --merge as a separate parameter that folks have to explicitly opt-in to, it's almost certainly not what a novice user wants. When first coded the --merge capability was automatically active, we encountered this usage pattern and realised that it was unhelpful, and so we introduced --merge as a way that users who genuinely wanted to merge could do so. In this case the user asked for a merge, and so the update was merged in. Most users should not be using --merge, they can simply use overwrite to replace their entire manifest each time.

Edit: folks who know what they're doing are of course welcome to edit the manifest file directly in order to rename parts, we don't stop them from doing that. But if they decide to regenerate their Bundle, and they ask us to preserve as much of what was there before as we can, then we give them what they asked for.
