### ISSUE TITLE
Running a merge with bundleId specified sees the bundleId remain the same.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#133]
Running a merge with bundleId specified sees the bundleId remain the same.

Eg

zowe cics-deploy generate bundle --bundleid nodeBundle --ow --merge

I expected the bundleId to be renamed to nodeBundle.  In fact it just added a bundlepart for nodejsapp called nodebundle.

Input/Output
zowe cics-deploy generate bundle --bundleid nodeBundle --ow --merge
    define : NODEJSAPP "nodeBundle" with startscript "server.js"
    create : nodejsapps\nodeBundle.nodejsapp
    create : nodejsapps\nodeBundle.profile
 overwrite : .zosattributes
     merge : META-INF\cics.xml
CICS Bundle generated with bundleid "nodeBundle"

Created bundle -
[RenameFailed.zip](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3156913/RenameFailed.zip)

Original
[OriginalTest.zip](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3156920/OriginalTest.zip)

**Comment by pcoop** [comment]
Hmm, interesting... I'm not sure what I think about this; I guess this does look odd, but it's also intentional-ish.

The _generate bundle_ command is for generating bundles, we don't have an _update bundle_, _change manifest_ or _add bundle_, at least not yet (we could have them in the future if we wanted). If the users requests --merge then they're asking for as much of the current bundle to be preserved as possible; the --bundleid is something we use when creating a new manifest... so it's not really relevant for --merge. At least, that's how it's coded, I appreciate that this edge case is a little peculiar. 

I guess we could change --bundleid so it can't be set if --merge is specified, that might be the right fix. Or we could change it so that --bundleid is only honoured with --merge if the existing manifest doesn't already have a bundleid set. Or we could change it as per this Issue and actually overwrite that part of the existing manifest (perhaps only if there was auto-generated content to add?). Or we could leave it as-is. I'm not sure that I have a preference.

**Comment by ChrisAtkinson1** [comment]
To add a bit to the the confusion on this - with this bundleVersion the merge works.

Eg

zowe cics-deploy generate bundle --bundleversion 2.3.1 --ow --merge
    define : NODEJSAPP "cics-nodejs-invoke" with startscript "server.js"
 overwrite : nodejsapps\cics-nodejs-invoke.nodejsapp
 overwrite : nodejsapps\cics-nodejs-invoke.profile
 overwrite : .zosattributes
     merge : META-INF\cics.xml
CICS Bundle generated with bundleid "cics-nodejs-invoke"

[NewVersion.zip](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3157875/NewVersion.zip)

**Comment by matthewpwilson** [comment]
Let's go with not allowing the version to be updated on merge either

**Comment by pcoop** [comment]
I'm having a bit of difficulty reproducing the problem at the moment... for me the bundleid is updating on a merge.

**Comment by matthewpwilson** [comment]
This works for me too, @ChrisAtkinson1 can you still reproduce this?

**Comment by ChrisAtkinson1** [comment]
Working correctly for me now.
