### ISSUE TITLE
When running --overwrite old parts are left untouched.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#135]
When running --overwrite old parts are left untouched, which I believe is correct behaviour.

In our test plan we had this: **Does --overwrite replace all files in the bundle?**
which Mark annotated with - _What does all files mean here? No files that are part of the Node.js application should change._ 

I believe that the META-INF should be replaced, and the nodejsapp bundle part added.

Any existing bundle parts ( eg TRANSACTION) that were in the old one will NOT be readded on overwrite.

Raising as a clarification question.

**Comment by ChrisAtkinson1** [comment]
Also .zosattributes will be replaced. Missed from above.

**Comment by pcoop** [comment]
I've not attempted to pro-actively delete files from the Bundle that might not be needed after an overwrite, it's unnecessarily risky to do so. There's no risk involved in leaving them be, just some small amount of bloat. 

If we actively delete things then: 
  - it's possible that they were still needed for something non-obvious (e.g. maybe the parts were going to be introspected by a Java/Node program), 
  - in order to get them all we'd need detailed knowledge of the pattern of side-files for every single resource type,
  - we'd need the equivalent of a _delete bundle_ (or _ungenerate bundle_ perhaps?) command, something we've not considered to be essential so far. If we want that I'd prefer to track it as an enhancement in it's own right.
