### ISSUE TITLE
Should the .zosattributes be overwritten on a merge

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#138]
I have a .zosattribute file in my directory that I customised ( eg is not the default)

When I run the merge command eg

zowe cics-deploy generate bundle  --bundleversion 16.1.1 --ow --merge

The .zosattribute file is overwritten with the default one.  Is this desired behaviour ?  

Output says it is overwritten.  But should it be if one is present on a merge.  I would expect it to be wiped on a overwrite - but maybe not the merge.
```
    define : NODEJSAPP "cics-nodejs-invoke" with startscript "server.js"
 overwrite : nodejsapps\cics-nodejs-invoke.nodejsapp
 overwrite : nodejsapps\cics-nodejs-invoke.profile
 overwrite : .zosattributes
     merge : META-INF\cics.xml
CICS Bundle generated with bundleid "cics-nodejs-invoke"
```

**Comment by pcoop** [comment]
I did discuss this one with Matthew back when developing this stuff, we thought at the time was that it was too much effort to attempt to merge the .zosattributes file with whatever already exists under that name.

Anyone who has gone to the effort to customise .zosattributes is clearly a power user, they shouldn't have any reason to use _generate bundle_. And besides, in order to use --merge you have to set --overwrite anyway, so they know that we'll splat anything we have to splat.

Note: --merge only applies to the manifest. There has been no attempt to make it apply to anything else.
