### ISSUE TITLE
Having non CICS standard but valid XML sees the generate command fail

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#158]
This is the error if xml is valid - but not as explorer or the CICS build toolkit would produce.

Command Error:
A failure occurred during CICS bundle generation.
 Reason = Existing CICS Manifest file found with unparsable content.

Eg this will fail due to the additional tns: bits

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tns:manifest xmlns="http://www.ibm.com/xmlns/prod/cics/bundle" id="TEST" bundleMajorVer="1" bundleMinorVer="0" bundleMicroVer="0" bundleVersion="1" bundleRelease="0" build="IntB-201809142129">
    <meta_directives>
        <timestamp>2018-10-23T13:52:21.596+01:00</timestamp>
    </meta_directives>
    <define name="TRAN" type="http://www.ibm.com/xmlns/prod/cics/bundle/TRANSACTION" path="TRAN.transaction"/>
    <define name="PROG1" type="http://www.ibm.com/xmlns/prod/cics/bundle/PROGRAM" path="PROG1.program"/>
</tns:manifest>

**Comment by pcoop** [comment]
Just to expand a little, we're (currently) using an XML parser for Node.js called 'xml2json', it doesn't resolve namespaces automatically which is at the heart of the issue here. I had previously attempted to use a package called xml2js, but that project appears to have stalled with no changes or accepted pull requests in 2 years. It didn't seem a sensible technology to rely on.

I can put some effort into trying to support namespaces properly, but since we only actually need it for a subset of the --merge scenarios, and --merge is itself a minor use-case, I was debating whether it's worth the effort of worrying about at this time.

--- 

Edit: The example XML above is actually invalid, so the tool's not wrong to complain about that. A better example would be:

`<tns:manifest **xmlns:tns**="http://www.ibm.com/xmlns/prod/cics/bundle" id="TEST" bundleMajorVer="1" bundleMinorVer="0" bundleMicroVer="0" bundleVersion="1" bundleRelease="0" build="IntB-201809142129">
<tns:meta_directives>
2018-10-23T13:52:21.596+01:00
</tns:meta_directives>
</tns:manifest>`

But that doesn't change the diagnostics, the same message is issued either way.
