### ISSUE TITLE
When the CMCI port or host are wrong in the cics profile - no debug output is given.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#219]
If the user or password differs from other profiles a warning is given.

Should we suppress the output like we do now - or issue a error from the cmci request ?

**Comment by pcoop** [comment]
Okay, several things going on here.

If the CMCI host is different to that of the other profiles, we currently issue a warning.
If the CMCI user is different to that of the other profiles, we also issue a warning message.

There's no such warning for the password being different, I am of the opinion that we should add that warning if the user and host names are the same, but have yet to do so.

If the hostname is invalid then (after issuing the warning) we'll not issue a message when the connection fails; if the port number is invalid then we don't issue an error for that either. The reason is that there's no consistency in the error information returned from the cics plug-in; sometimes there's a useful error message, sometimes there's a large binary dump of information filling many pages of the screen. Other problems may include attempting to connect to a secure CMCI port with an unsecure connection, invalid credentials, the port number is in use by something else, a pre TS 5.5 version of CPSM, etc.. The cics plug-in rarely returns information that will be meaningful to the user in these situations, displaying its error text is liable to be an unhelpful.

We could implement a heuristic and only display the error information if the message is short enough, though the contents of that error may still be unhelpful to the end user. Or we could issue a different message indicating that cics-deploy tried and failed to connect to CICS for further information, perhaps offering a Zowe command the user could run for themselves to investigate further. Or we could leave it as is and simply terminate after displaying as much as we can. I'm open to suggestions.

**Comment by pcoop** [comment]
I've experimented with issuing the following message from cics-deploy:

```
An attempt to query the remote CICSplex has failed. Consider issuing the following command to investigate why:

zowe cics get resource CICSRegion --region-name <SCOPE> --cics-plex <CICSPLEX>
```

The output of that might be something like the following (with no connection):

```
HTTP(S) client encountered an error. Request could not be initiated to host.
Review connection details (host, port) and ensure correctness.

Host:      winmvs2c.hursley.ibm.com
Port:      <PORT>
Base Path:
Resource:  /CICSSystemManagement/CICSRegion/CAPLEX/AOR
Request:   GET
Headers:   []
Payload:   undefined
```

That example is relatively neat. Or less neat (with the wrong port):

```
Did not receive the expected response from CMCI REST API.
response:
  xmlns:              http://www.ibm.com/xmlns/prod/CICS/smw2int
  xmlns:xsi:          http://www.w3.org/2001/XMLSchema-instance
  xsi:schemaLocation: http://www.ibm.com/xmlns/prod/CICS/smw2int http://winmvs2c.hursley.ibm.com:20020/CICSSystemManagement/schema/CICSSystemManagement.xsd
  version:            3.0
  connect_version:    0610
  resultsummary:
    api_source:        CICSPlex SM
    api_function:      CONNECT
    api_response1:     1028
    api_response2:     1282
    api_response1_alt: INVALIDPARM
    api_response2_alt: CONTEXT
    recordcount:       0
```

Or (wrong protocol):

```
Error: write EPROTO 13772:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:openssl\ssl\record\ssl3_record.c:252:
```

And so forth. I've seen large binary dumps of data in some instances. Suggesting the user run that command is at least better than having such weirdness issued from our command. I wouldn't really expect the user to make much sense of it though, not in general.

**Comment by pcoop** [comment]
Consider issuing "An attempt to query the remote CICSplex using the cics plug-in has failed." or similar.

**Comment by matthewpwilson** [comment]
@ChrisAtkinson1 please can you confirm if you're happy with the new error message Paul has implemented.

**Comment by ChrisAtkinson1** [comment]
$ zowe cics-deploy push bundle --name CICSJSON  --ow
An attempt to query the remote CICSplex using the cics plug-in has failed.
PUSH operation completed

Seems fine to me
