### ISSUE TITLE
MVS passwords not matching error message

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#253]
Think this is a good message.  But you can specify the same password in upper or lower case and it still works however you specify it.  

So if you UPPER case one and Lower case another ( or a mixture ) when running PUSH you get this error 

Command Error:
A failure occurred during CICS bundle pushing.
 Reason = Different passwords are specified for the same user ID in the zosmf and ssh configurations.

Should we cope with the casing or just make the user enter the same passwords ?

**Comment by pcoop** [comment]
According to the RACF docs case sensitivity/insensitivity for passwords is configurable: https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.icha700/amcp.htm . Some users may have case sensitive passwords, and since a case error is a particularly easy mistake for a user to make, I'm inclined to default towards detecting it.

I may be mistaken, but I think passphrases are generally mixed case too, it's just the older style of passwords that often aren't.

**Comment by ChrisAtkinson1** [comment]
I am using the old style.

**Comment by ChrisAtkinson1** [comment]
Agree to accept the message detecting difference.
