### ISSUE TITLE
Getting connection refused. On a deploy request.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#259]
zowe cics-deploy deploy bundle --name NONPM --bundledir /u/atkinc/bundles/CICSJSON_1.0.0/
Command Error:
A failure occurred during CICS bundle deployment.
 Reason = Validation of --cicshlq dataset failed: z/OSMF REST API Error:
http(s) request error event called
Error: connect ECONNREFUSED 9.20.5.0:30270

Log

[refused.log](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3282095/refused.log)

**Comment by pcoop** [comment]
The remote server rejected the request, the server logs might show something to help explain why. Maybe the zosmf service was stopped for some reason?

**Comment by pcoop** [comment]
It's clear from the log (as well as the command line above) that the zosmf configuration must be coming from the default zosmf profile.

The error message reports that the connection was to 9.20.5.0 (that's winmvs2c.hursley.ibm.com) and port number 30270. The intended port number was presumably _32070_ rather than _30270_. So an error in the profile?

If I run the following command:

```
zowe zosmf check status --host winmvs2c.hursley.ibm.com --port 30270
```

I see the same error message, but if I change to:

```
zowe zosmf check status --host winmvs2c.hursley.ibm.com --port 32070
```

I see the expected response.

**Comment by ChrisAtkinson1** [comment]
Yes thanks typo on the port.
