### ISSUE TITLE
bundle generate should generate .zosattributes file

### ISSUE THREAD

**Issue by matthewpwilson** [IBM/zowe-cli-cics-deploy-plugin#46]
it would be helpful `cics-deploy generate bundle` generated a tempalte .zosattributes file with a basic set of filetypes, including things like .profile.

**Comment by matthewpwilson** [comment]
Here's the file I've been playing with as a starting point:

```
# Don't upload node_modules
node_modules -
# Don't upload things that start with dots
.* -

# Upload images in binary
*.jpg binary binary
*.png binary binary
*.gif binary binary
*.zip binary binary
*.eot binary binary
*.svg binary binary
*.ttf binary binary
*.woff binary binary

# Convert Node.js profiles to EBCDIC
*.profile ISO8859-1 IBM-1047
```

**Comment by markcocker** [comment]
Instead of "Node.js profiles" I suggest  "CICS Node.js profiles".

**Comment by pcoop** [comment]
We did have a quick chat about what to do if the .zosattributes file already exists... fail, overwrite or merge? If we do anything fancy, should it have the same semantics as whatever we implement for the Bundle manifest?

The conclusion was that we should probably just fail. Anything else gets a bit complicated, we just have to be clear in the error message that we're failing over a clash on this file rather than anything else. Thereafter the user can delete/rename the file if they want to do so before rerunning Generate Bundle.
