### ISSUE TITLE
Error scenarios should set return code and output to stderr

### ISSUE THREAD

**Issue by matthewpwilson** [IBM/zowe-cli-cics-deploy-plugin#5]
In error scenarios we're currently setting rc=0. For scripting of the command it would be useful to tell if the generate has failed, so that the script can skip any further actions and report errors. 
For example, if I don't have write permission to the current directory so the bundle metadata can't be created I'd like to see rc > 0.

Also it would be useful if error messages could be sent to stderr. This allows scripts to extract error messages from informational messages.

**Comment by markcocker** [comment]
I looked in https://zowe.github.io/docs-site/latest/ but there doesn't seem to be a Zowe standard for return code values.

**Comment by pcoop** [comment]
I've not been able to find an Imperative/Zowe API to set a return code. I've had a play with process.exit(), and while that may technically work, it's not very friendly to the test automation. The Handler tests don't complete with process.exit() on errors.

I can send the error messages to stderr rather than stdout, I'll put a change through for that, but the response codes issue remains TBD.

**Comment by pcoop** [comment]
Oh, just for the record, I tried throwing an Exception from our handler to see if that would cause nice diagnostics... it had the unfortunate result of dumping a stack trace to the console and informing the user to contact the developers of the plugin. That's not a viable option for setting a non-zero return code.

**Comment by matthewpwilson** [comment]
Fixed.
