### ISSUE TITLE
Parameter names should use hyphens to separate words

### ISSUE THREAD

**Issue by markcocker** [IBM/zowe-cli-cics-deploy-plugin#57]
From looking at the guidelines [CommandFormatStandards](https://github.com/zowe/zowe-cli/blob/master/docs/CommandFormatStandards.md) under heading **General Naming Conventions** suggest hyphenation to separate words in options. Examples can be seen in the [CLI Reference Document](https://zowe.github.io/docs-site/latest/CLIReference_Zowe.pdf) eg. `--region-name`.

The cics-deploy plugin by comparison does not use hyphens for most parameter names eg. `--csdgroup` and `--targetstate` except for parameters that already exist elsewhere such as profile and global parameters eg. `--cics-deploy-profile`.

As Zowe CLI users will typically use a mixture of cics-deploy and other commands, conforming to the Zowe standards will help usability.

**Comment by pcoop** [comment]
We can change such things if you want. The names were usually chosen either to match DFHDPLOY (which is the doc folks will have to read if something goes wrong), or based on our original Boxnote design. 

One drawback of using hyphens is that they become relatively difficult to generate in JSON (which is relevant to anyone using the API to call the code). For example, you can script:

  _arguments.bundledir = "whatever";_

quite easily, but to do the equivalent with a hyphen in the name requires:

  _arguments["bundle-dir"] = "whatever";_

it can be done, but it's less obvious.

**Comment by pcoop** [comment]
I've attempted to think through what we should change in order to do this. It's not always obvious what a 'word' is, so some of it is open to debate. In some cases the abbreviated form of a long name will introduce a clash, so if we want to avoid that it'll take more work (eg _cics-hlq_ and _cpsm-hlq_ would both abbreviate to _ch_). We can chose to retain our current names in addition to adding the new hyphenated variants if we want to do so.

It's curious that Zowe's parameters for profiles don't follow their naming convention; for example, _--zp_ is not a valid substitute for _--zosmf-profile_! I guess that's why they say 'should' when referring to the convention rather than 'must'.



Generate Bundle:

--bundleid ==> --bundle-id | bundleid | bi | b
--bundleversion ==> bundle-version | bundleversion | bv
--nodejsapp [unchanged] ==> nodejsapp | nja | nj | n
--startscript ==> start-script | startscript | ss | s
--port [unchanged] ==> port | p
--overwrite [unchanged] ==> overwrite | ow
--merge [unchanged] ==> merge | me


Push Bundle:

--name [unchanged] ==> name | n
--targetdir ==> target-dir | targetdir | td
--cicsplex ==> cics-plex | cicsplex | cp
--scope [unchanged] ==> scope | sc
--csdgroup ==> csd-group | csdgroup | cg
--resgroup ==> res-group | resgroup | rg
--cicshlq ==> cics-high-level-qualifier | cics-hlq | ch
--cpsmhlq ==> cpsm-high-level-qualifier | cpsm-hlq | cph   [Note, the ch is not available]
--description [unchanged] ==> description | desc
--jobcard ==> job-card | jobcard | jc
--timeout ==> time-out | timeout | to
--targetstate ==> target-state | targetstate | ts
--verbose [unchanged] ==> verbose | v
--overwrite [unchanged] ==> overwrite | ow

**Comment by markcocker** [comment]
Time-out > timeout
cics-plex > cicsplex
high-level-qualifier > hlq
target-dir > target-directory

**Comment by pcoop** [comment]
Regarding the _cicsplex_ parameter, I've just noticed that the zowe cics plugin calls it _cics-plex_ - we probably ought to do so too for the sake of consistency.
