### ISSUE TITLE
Should PUSH detect if npm_modules directory is removed from .zosattributes ?

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#86]
If you edit the .zosatttribute file to allow npm_modules directory to be uploaded the npm_modules are uploaded.

The PUSH then does a npm install of the .package.json file.

If the modules are all the same they are just reinstalled.  So wastes time.

Maybe a warning should be given, as perhaps there maybe a use case for the user uploading something that is not in the package.json ?

**Comment by pcoop** [comment]
Seems to me that if a power user decides to tweak .zosattributes we should let them - that's what it's there for after all. We have to run the remote 'npm install' regardless, otherwise they'll have native modules for the wrong platform.

As for issuing a warning... I suppose we could do that... but as it was their decision to override the defaults then it seems unnecessary. Besides, we don't really have the concept of a warning; we either issue a message so that they know what happened afterwards (which they can infer by the horribly slow upload anyway), or we refuse to process the request.

**Comment by markcocker** [comment]
Suggested solution is for file upload to provide verbose output, so will raise an issue on Zowe CLI.

https://github.com/zowe/zowe-cli/issues/355

**Comment by matthewpwilson** [comment]
As part of #87 I'm hooking the progress bar into `upload dir-to-uss` which will show which file it's uploading.  We don't think there's much more we can do than that.
